// Generated by gencpp from file arm_lib/Fk.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_FK_H
#define ARM_LIB_MESSAGE_FK_H

#include <ros/service_traits.h>


#include <arm_lib/FkRequest.h>
#include <arm_lib/FkResponse.h>


namespace arm_lib
{

struct Fk
{

typedef FkRequest Request;
typedef FkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Fk
} // namespace arm_lib


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_lib::Fk > {
  static const char* value()
  {
    return "7853f73d8810c73a397dd4eacf4f66bb";
  }

  static const char* value(const ::arm_lib::Fk&) { return value(); }
};

template<>
struct DataType< ::arm_lib::Fk > {
  static const char* value()
  {
    return "arm_lib/Fk";
  }

  static const char* value(const ::arm_lib::Fk&) { return value(); }
};


// service_traits::MD5Sum< ::arm_lib::FkRequest> should match
// service_traits::MD5Sum< ::arm_lib::Fk >
template<>
struct MD5Sum< ::arm_lib::FkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::Fk >::value();
  }
  static const char* value(const ::arm_lib::FkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::FkRequest> should match
// service_traits::DataType< ::arm_lib::Fk >
template<>
struct DataType< ::arm_lib::FkRequest>
{
  static const char* value()
  {
    return DataType< ::arm_lib::Fk >::value();
  }
  static const char* value(const ::arm_lib::FkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_lib::FkResponse> should match
// service_traits::MD5Sum< ::arm_lib::Fk >
template<>
struct MD5Sum< ::arm_lib::FkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::Fk >::value();
  }
  static const char* value(const ::arm_lib::FkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::FkResponse> should match
// service_traits::DataType< ::arm_lib::Fk >
template<>
struct DataType< ::arm_lib::FkResponse>
{
  static const char* value()
  {
    return DataType< ::arm_lib::Fk >::value();
  }
  static const char* value(const ::arm_lib::FkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_LIB_MESSAGE_FK_H
