// Generated by gencpp from file arm_lib/FkResponse.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_FKRESPONSE_H
#define ARM_LIB_MESSAGE_FKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_lib
{
template <class ContainerAllocator>
struct FkResponse_
{
  typedef FkResponse_<ContainerAllocator> Type;

  FkResponse_()
    : position()  {
    }
  FkResponse_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::arm_lib::FkResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_lib::FkResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FkResponse_

typedef ::arm_lib::FkResponse_<std::allocator<void> > FkResponse;

typedef boost::shared_ptr< ::arm_lib::FkResponse > FkResponsePtr;
typedef boost::shared_ptr< ::arm_lib::FkResponse const> FkResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_lib::FkResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_lib::FkResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_lib::FkResponse_<ContainerAllocator1> & lhs, const ::arm_lib::FkResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_lib::FkResponse_<ContainerAllocator1> & lhs, const ::arm_lib::FkResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_lib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_lib::FkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_lib::FkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::FkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::FkResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::FkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::FkResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_lib::FkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50410efb3480c63b23b8b5fe2bea331a";
  }

  static const char* value(const ::arm_lib::FkResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50410efb3480c63bULL;
  static const uint64_t static_value2 = 0x23b8b5fe2bea331aULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_lib::FkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_lib/FkResponse";
  }

  static const char* value(const ::arm_lib::FkResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_lib::FkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] position\n"
"\n"
;
  }

  static const char* value(const ::arm_lib::FkResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_lib::FkResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FkResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_lib::FkResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_lib::FkResponse_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_LIB_MESSAGE_FKRESPONSE_H
