// Generated by gencpp from file arm_lib/Ik.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_IK_H
#define ARM_LIB_MESSAGE_IK_H

#include <ros/service_traits.h>


#include <arm_lib/IkRequest.h>
#include <arm_lib/IkResponse.h>


namespace arm_lib
{

struct Ik
{

typedef IkRequest Request;
typedef IkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Ik
} // namespace arm_lib


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_lib::Ik > {
  static const char* value()
  {
    return "be8af31935508c52c6f10da29410f87d";
  }

  static const char* value(const ::arm_lib::Ik&) { return value(); }
};

template<>
struct DataType< ::arm_lib::Ik > {
  static const char* value()
  {
    return "arm_lib/Ik";
  }

  static const char* value(const ::arm_lib::Ik&) { return value(); }
};


// service_traits::MD5Sum< ::arm_lib::IkRequest> should match
// service_traits::MD5Sum< ::arm_lib::Ik >
template<>
struct MD5Sum< ::arm_lib::IkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::Ik >::value();
  }
  static const char* value(const ::arm_lib::IkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::IkRequest> should match
// service_traits::DataType< ::arm_lib::Ik >
template<>
struct DataType< ::arm_lib::IkRequest>
{
  static const char* value()
  {
    return DataType< ::arm_lib::Ik >::value();
  }
  static const char* value(const ::arm_lib::IkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_lib::IkResponse> should match
// service_traits::MD5Sum< ::arm_lib::Ik >
template<>
struct MD5Sum< ::arm_lib::IkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::Ik >::value();
  }
  static const char* value(const ::arm_lib::IkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::IkResponse> should match
// service_traits::DataType< ::arm_lib::Ik >
template<>
struct DataType< ::arm_lib::IkResponse>
{
  static const char* value()
  {
    return DataType< ::arm_lib::Ik >::value();
  }
  static const char* value(const ::arm_lib::IkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_LIB_MESSAGE_IK_H
