// Generated by gencpp from file arm_lib/IkRequest.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_IKREQUEST_H
#define ARM_LIB_MESSAGE_IKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_lib
{
template <class ContainerAllocator>
struct IkRequest_
{
  typedef IkRequest_<ContainerAllocator> Type;

  IkRequest_()
    : link_lengths()
    , joint_positions()
    , positions()  {
    }
  IkRequest_(const ContainerAllocator& _alloc)
    : link_lengths(_alloc)
    , joint_positions(_alloc)
    , positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _link_lengths_type;
  _link_lengths_type link_lengths;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_positions_type;
  _joint_positions_type joint_positions;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::arm_lib::IkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_lib::IkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IkRequest_

typedef ::arm_lib::IkRequest_<std::allocator<void> > IkRequest;

typedef boost::shared_ptr< ::arm_lib::IkRequest > IkRequestPtr;
typedef boost::shared_ptr< ::arm_lib::IkRequest const> IkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_lib::IkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_lib::IkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_lib::IkRequest_<ContainerAllocator1> & lhs, const ::arm_lib::IkRequest_<ContainerAllocator2> & rhs)
{
  return lhs.link_lengths == rhs.link_lengths &&
    lhs.joint_positions == rhs.joint_positions &&
    lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_lib::IkRequest_<ContainerAllocator1> & lhs, const ::arm_lib::IkRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_lib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_lib::IkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_lib::IkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::IkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::IkRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::IkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::IkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_lib::IkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "070563dd2198a94495c4bd7fe8a5484c";
  }

  static const char* value(const ::arm_lib::IkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x070563dd2198a944ULL;
  static const uint64_t static_value2 = 0x95c4bd7fe8a5484cULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_lib::IkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_lib/IkRequest";
  }

  static const char* value(const ::arm_lib::IkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_lib::IkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] link_lengths\n"
"float64[] joint_positions\n"
"float64[] positions\n"
;
  }

  static const char* value(const ::arm_lib::IkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_lib::IkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.link_lengths);
      stream.next(m.joint_positions);
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_lib::IkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_lib::IkRequest_<ContainerAllocator>& v)
  {
    s << indent << "link_lengths[]" << std::endl;
    for (size_t i = 0; i < v.link_lengths.size(); ++i)
    {
      s << indent << "  link_lengths[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.link_lengths[i]);
    }
    s << indent << "joint_positions[]" << std::endl;
    for (size_t i = 0; i < v.joint_positions.size(); ++i)
    {
      s << indent << "  joint_positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_positions[i]);
    }
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_LIB_MESSAGE_IKREQUEST_H
